// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CreateSessionRequest is an autogenerated mock type for the CreateSessionRequest type
type CreateSessionRequest struct {
	mock.Mock
}

// GetAudience provides a mock function with given fields:
func (_m *CreateSessionRequest) GetAudience() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetClientID provides a mock function with given fields:
func (_m *CreateSessionRequest) GetClientID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetRedirectURI provides a mock function with given fields:
func (_m *CreateSessionRequest) GetRedirectURI() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewCreateSessionRequest creates a new instance of CreateSessionRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateSessionRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateSessionRequest {
	mock := &CreateSessionRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
