// Code generated by lab.weave.nl/devops/proto-istio-auth-generator, DO NOT EDIT.
package onboardingscopes

// DataSourceServiceConvertBSNToPseudonym contains the scope for ConvertBSNToPseudonym in the DataSourceService service
const DataSourceServiceConvertBSNToPseudonym = "convertbsn"	

// GetAllScopes retrieve all available scopes
func GetAllScopes() []string{
	return []string{
			DataSourceServiceConvertBSNToPseudonym,
	}
}
