// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// InfoRestarter is an autogenerated mock type for the InfoRestarter type
type InfoRestarter struct {
	mock.Mock
}

// RestartInfoServices provides a mock function with given fields:
func (_m *InfoRestarter) RestartInfoServices() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
