// Code generated by lab.weave.nl/weave/generator, DO NOT EDIT.

package models

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jinzhu/gorm"
)

// Script Relational Model
type Script struct {
	ID             uuid.UUID  `sql:"default:uuid_generate_v4()" gorm:"primary_key" json:"id"` // primary key
	EventType      string     `json:"event_type"`
	OrganisationID uuid.UUID  `gorm:"index:idx_script_organisation_id" json:"organisation_id"`
	Script         string     `json:"script"`
	CreatedAt      time.Time  `json:"created_at"`
	DeletedAt      *time.Time `json:"deleted_at"`
	UpdatedAt      time.Time  `json:"updated_at"`
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m Script) TableName() string {
	return "scripts"
}

// ScriptDB is the implementation of the storage interface for
// Script.
type ScriptDB struct {
	Db *gorm.DB // Deprecated: Use ScriptDB.DB() instead.
}

// NewScriptDB creates a new storage type.
func NewScriptDB(db *gorm.DB) *ScriptDB {
	return &ScriptDB{Db: db}
}

// DB returns the underlying database.
func (m *ScriptDB) DB() interface{} {
	return m.Db
}

// TableName returns the table name of the associated model
//
// Deprecated: Use db.Model(Script{}) instead.
func (m *ScriptDB) TableName() string {
	return "scripts"
}

// CRUD Functions

// Get returns a single Script as a Database Model
func (m *ScriptDB) Get(ctx context.Context, id uuid.UUID) (*Script, error) {
	var native Script
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of Script
func (m *ScriptDB) List(ctx context.Context) ([]*Script, error) {
	var objs []*Script
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *ScriptDB) Add(ctx context.Context, model *Script) error {
	err := m.Db.Create(model).Error
	if err != nil {
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *ScriptDB) Update(ctx context.Context, model *Script) error {
	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *ScriptDB) Delete(ctx context.Context, id uuid.UUID) error {
	err := m.Db.Where("id = ?", id).Delete(&Script{}).Error
	if err != nil {
		return err
	}

	return nil
}
