// Code generated by lab.weave.nl/weave/generator, DO NOT EDIT.

package models

import (
	"github.com/jinzhu/gorm"
	"lab.weave.nl/weave/generator/gen/auth"
)

func GetModels() []interface{} {
	return []interface{}{
		auth.JWT{},
		Client{},
		Consent{},
		Device{},
		EmailAddress{},
		PhoneNumber{},
		User{},
	}
}

func AddForeignKeys(db *gorm.DB) []error {
	var errs []error

	if err := db.Table("consents").AddForeignKey("client_id", "clients(id)", "NO ACTION", "NO ACTION").Error; err != nil {
		errs = append(errs, err)
	}

	if err := db.Table("consents").AddForeignKey("user_id", "users(id)", "NO ACTION", "NO ACTION").Error; err != nil {
		errs = append(errs, err)
	}

	if err := db.Table("devices").AddForeignKey("user_id", "users(id)", "NO ACTION", "NO ACTION").Error; err != nil {
		errs = append(errs, err)
	}

	if err := db.Table("email_addresses").AddForeignKey("user_id", "users(id)", "NO ACTION", "NO ACTION").Error; err != nil {
		errs = append(errs, err)
	}

	if err := db.Table("phone_numbers").AddForeignKey("user_id", "users(id)", "NO ACTION", "NO ACTION").Error; err != nil {
		errs = append(errs, err)
	}

	return errs
}
