// Code generated by lab.weave.nl/weave/generator, DO NOT EDIT.

package models

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jinzhu/gorm"
)

// Device Relational Model
type Device struct {
	ID        uuid.UUID  `sql:"default:uuid_generate_v4()" gorm:"primary_key" json:"id"` // primary key
	Code      string     `gorm:"unique_index:idx_device_code" json:"code"`               // unique index: "code"
	Secret    string     `json:"secret"`
	User      *User      `json:"user"`
	UserID    uuid.UUID  `gorm:"index:idx_device_user_id" json:"user_id"`
	CreatedAt time.Time  `json:"created_at"`
	DeletedAt *time.Time `json:"deleted_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m Device) TableName() string {
	return "devices"
}

// DeviceDB is the implementation of the storage interface for
// Device.
type DeviceDB struct {
	Db *gorm.DB // Deprecated: Use DeviceDB.DB() instead.
}

// NewDeviceDB creates a new storage type.
func NewDeviceDB(db *gorm.DB) *DeviceDB {
	return &DeviceDB{Db: db}
}

// DB returns the underlying database.
func (m *DeviceDB) DB() interface{} {
	return m.Db
}

// TableName returns the table name of the associated model
//
// Deprecated: Use db.Model(Device{}) instead.
func (m *DeviceDB) TableName() string {
	return "devices"
}

// CRUD Functions

// Get returns a single Device as a Database Model
func (m *DeviceDB) Get(ctx context.Context, id uuid.UUID) (*Device, error) {
	var native Device
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of Device
func (m *DeviceDB) List(ctx context.Context) ([]*Device, error) {
	var objs []*Device
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *DeviceDB) Add(ctx context.Context, model *Device) error {
	err := m.Db.Create(model).Error
	if err != nil {
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *DeviceDB) Update(ctx context.Context, model *Device) error {
	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *DeviceDB) Delete(ctx context.Context, id uuid.UUID) error {
	err := m.Db.Where("id = ?", id).Delete(&Device{}).Error
	if err != nil {
		return err
	}

	return nil
}
