// Code generated by lab.weave.nl/weave/generator, DO NOT EDIT.

package models

import (
	"context"
	"time"

	"github.com/gofrs/uuid"
	"github.com/jinzhu/gorm"
)

// EmailAddress Relational Model
type EmailAddress struct {
	ID                uuid.UUID  `sql:"default:uuid_generate_v4()" gorm:"primary_key" json:"id"` // primary key
	EmailAddress      string     `json:"email_address"`
	User              *User      `json:"user"`
	UserID            uuid.UUID  `gorm:"index:idx_email_address_user_id" json:"user_id"`
	VerificationToken string     `json:"verification_token"`
	Verified          bool       `json:"verified"`
	CreatedAt         time.Time  `json:"created_at"`
	DeletedAt         *time.Time `json:"deleted_at"`
	UpdatedAt         time.Time  `json:"updated_at"`
}

// TableName overrides the table name settings in Gorm to force a specific table name
// in the database.
func (m EmailAddress) TableName() string {
	return "email_addresses"
}

// EmailAddressDB is the implementation of the storage interface for
// EmailAddress.
type EmailAddressDB struct {
	Db *gorm.DB // Deprecated: Use EmailAddressDB.DB() instead.
}

// NewEmailAddressDB creates a new storage type.
func NewEmailAddressDB(db *gorm.DB) *EmailAddressDB {
	return &EmailAddressDB{Db: db}
}

// DB returns the underlying database.
func (m *EmailAddressDB) DB() interface{} {
	return m.Db
}

// TableName returns the table name of the associated model
//
// Deprecated: Use db.Model(EmailAddress{}) instead.
func (m *EmailAddressDB) TableName() string {
	return "email_addresses"
}

// CRUD Functions

// Get returns a single EmailAddress as a Database Model
func (m *EmailAddressDB) Get(ctx context.Context, id uuid.UUID) (*EmailAddress, error) {
	var native EmailAddress
	err := m.Db.Table(m.TableName()).Where("id = ?", id).Find(&native).Error
	if err == gorm.ErrRecordNotFound {
		return nil, err
	}

	return &native, err
}

// List returns an array of EmailAddress
func (m *EmailAddressDB) List(ctx context.Context) ([]*EmailAddress, error) {
	var objs []*EmailAddress
	err := m.Db.Table(m.TableName()).Find(&objs).Error
	if err != nil && err != gorm.ErrRecordNotFound {
		return nil, err
	}

	return objs, nil
}

// Add creates a new record.
func (m *EmailAddressDB) Add(ctx context.Context, model *EmailAddress) error {
	err := m.Db.Create(model).Error
	if err != nil {
		return err
	}

	return nil
}

// Update modifies a single record.
func (m *EmailAddressDB) Update(ctx context.Context, model *EmailAddress) error {
	obj, err := m.Get(ctx, model.ID)
	if err != nil {
		return err
	}
	err = m.Db.Model(obj).Updates(model).Error

	return err
}

// Delete removes a single record.
func (m *EmailAddressDB) Delete(ctx context.Context, id uuid.UUID) error {
	err := m.Db.Where("id = ?", id).Delete(&EmailAddress{}).Error
	if err != nil {
		return err
	}

	return nil
}
