// Code generated by mockery v2.4.0-beta. DO NOT EDIT.

package mock

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "github.com/nID-sourcecode/nid-core/svc/wallet-rpc/proto"
)

// WalletClient is an autogenerated mock type for the WalletClient type
type WalletClient struct {
	mock.Mock
}

// CreateConsent provides a mock function with given fields: ctx, in, opts
func (_m *WalletClient) CreateConsent(ctx context.Context, in *proto.CreateConsentRequest, opts ...grpc.CallOption) (*proto.ConsentResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.ConsentResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CreateConsentRequest, ...grpc.CallOption) *proto.ConsentResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.ConsentResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.CreateConsentRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBSNForPseudonym provides a mock function with given fields: ctx, in, opts
func (_m *WalletClient) GetBSNForPseudonym(ctx context.Context, in *proto.GetBSNForPseudonymRequest, opts ...grpc.CallOption) (*proto.GetBSNForPseudonymResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *proto.GetBSNForPseudonymResponse
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetBSNForPseudonymRequest, ...grpc.CallOption) *proto.GetBSNForPseudonymResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetBSNForPseudonymResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetBSNForPseudonymRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
