apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: "istio-system"
spec:
  mtls:
    mode: STRICT
---
# FIXME: enable mtls before production: https://lab.weave.nl/twi/core/-/issues/43
apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "jwks"
spec:
  selector:
    matchLabels:
      app: jwks
  mtls:
    mode: PERMISSIVE
