apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: scopeverification-jwt-auth
spec:
  jwtRules:
    - issuer: "auth.{{ .Release.Namespace }}"
      jwksUri: http://jwks.{{ .Release.Namespace }}.svc.cluster.local/v1/jwt/jwks
      forwardOriginalToken: true
  selector:
    matchLabels:
      nid-datasource: enabled
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "scopeverification-jwt-auth-policy"
spec:
  selector:
    matchLabels:
      nid-datasource: enabled
  action: DENY
  rules:
  - from:
    - source:
        notRequestPrincipals: ["*"]
