{{- range .Values.externalroutes }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: {{ .name }}
spec:
  hosts:
    {{- range .routes}}
    - {{ . | quote }}
    {{- end}}
  location: MESH_EXTERNAL
  ports:
    - number: 443
      name: https
      protocol: TLS
  resolution: DNS
---
{{- end}}
{{- if .Values.documentation.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: external-svc-bucket
spec:
  hosts:
  - storage.googleapis.com
  - "*.storage.googleapis.com"
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: TLS
  resolution: NONE
---
{{- end}}