// Code generated by lab.weave.nl/devops/proto-istio-auth-generator, DO NOT EDIT.
package documentationscopes

// DocumentationGetFile contains the scope for GetFile in the Documentation service
const DocumentationGetFile = "get_documentation_file"	

// DocumentationListDirectoryFiles contains the scope for ListDirectoryFiles in the Documentation service
const DocumentationListDirectoryFiles = "list_documentation_directory"	

// DocumentationListRepositoryRefs contains the scope for ListRepositoryRefs in the Documentation service
const DocumentationListRepositoryRefs = "list_documentation_repository_refs"	

// GetAllScopes retrieve all available scopes
func GetAllScopes() []string{
	return []string{
			DocumentationGetFile,
			DocumentationListDirectoryFiles,
			DocumentationListRepositoryRefs,
	}
}
