// Code generated by lab.weave.nl/weave/generator, DO NOT EDIT.

package models

import (
	"github.com/jinzhu/gorm"
)

func GetModels() []interface{} {
	return []interface{}{
		Address{},
		BankAccount{},
		ContactDetail{},
		SavingsAccount{},
		User{},
	}
}

func AddForeignKeys(db *gorm.DB) []error {
	var errs []error

	if err := db.Table("bank_accounts").AddForeignKey("user_id", "users(id)", "NO ACTION", "NO ACTION").Error; err != nil {
		errs = append(errs, err)
	}

	if err := db.Table("contact_details").AddForeignKey("address_id", "addresses(id)", "NO ACTION", "NO ACTION").Error; err != nil {
		errs = append(errs, err)
	}

	if err := db.Table("contact_details").AddForeignKey("user_id", "users(id)", "NO ACTION", "NO ACTION").Error; err != nil {
		errs = append(errs, err)
	}

	if err := db.Table("savings_accounts").AddForeignKey("bank_account_id", "bank_accounts(id)", "NO ACTION", "NO ACTION").Error; err != nil {
		errs = append(errs, err)
	}

	return errs
}
