{{- range .Values.secrets}}
apiVersion: v1
kind: Secret
metadata:
  name: {{required "A valid secret name should be supplied" .name}}
  namespace: {{ default $.Release.Namespace .namespace }}
type: Opaque
stringData:
{{toYaml (required (printf "A valid (yaml) content for the secret \"%s\" should be supplied" .name)  .data) | indent 2}}
---
{{- end}}
