{{- if .Values.dashboard.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
  labels:
    account: dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-admin
subjects:
- kind: ServiceAccount
  name: dashboard
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
{{- end}}
{{- if (and .Values.integrationtests .Values.integrationtests.enabled ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: integration-tests
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: port-forward-and-get-logs
rules:
  - apiGroups: [ "" ]
    resources: [ "pods/portforward" ]
    verbs: [ "get", "list", "create" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/log" ]
    verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: integration-tests-binding
subjects:
- kind: ServiceAccount
  name: integration-tests
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: port-forward-and-get-logs
---
  {{- end}}
  {{- if .Values.wallet.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet
  labels:
    account: wallet
---
  {{- end}}
  {{- if .Values.autobsn.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autobsn
  labels:
    account: autobsn
---
  {{- end}}
  {{- if .Values.luarunner.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: luarunner
  labels:
    account: luarunner
---
  {{- end}}
  {{- if .Values.nginx.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx
  labels:
    account: nginx
---
  {{- end}}
  {{- if .Values.filters.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nidfilter
  labels:
    account: nidfilter
---
  {{- end}}
  