{{- if .Values.dashboard.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard
  labels:
    account: dashboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: dashboard
    namespace: {{ .Release.Namespace }}
  {{- end}}
  {{- if (and .Values.integrationtests .Values.integrationtests.enabled ) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: integration-tests
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: port-forward-and-get-logs
rules:
  - apiGroups: [ "" ]
    resources: [ "pods/portforward" ]
    verbs: [ "get", "list", "create" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "pods/log" ]
    verbs: [ "get", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: integration-tests-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: port-forward-and-get-logs
subjects:
  - kind: ServiceAccount
    name: integration-tests
    namespace: {{ .Release.Namespace }}
---
  {{- end}}
  {{- if .Values.wallet.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wallet
  labels:
    account: wallet
---
  {{- end}}
  {{- if .Values.auth.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  labels:
    account: auth
---
  {{- end}}
  {{- if .Values.autobsn.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autobsn
  labels:
    account: autobsn
---
  {{- end}}
  {{- if .Values.luarunner.enabled}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: luarunner
  labels:
    account: luarunner
---
  {{- end}}
  