// Code generated by lab.weave.nl/weave/generator, DO NOT EDIT.

package models

import (
	"github.com/jinzhu/gorm"
)

func GetModels() []interface{} {
	return []interface{}{
		Script{},
		ScriptSource{},
	}
}

func AddForeignKeys(db *gorm.DB) []error {
	var errs []error

	if err := db.Table("script_sources").AddForeignKey("script_id", "scripts(id)", "NO ACTION", "NO ACTION").Error; err != nil {
		errs = append(errs, err)
	}

	return errs
}
