apiVersion: v2

#TODO rename namespace config
name: cluster-config
description: Nid cluster config chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0


dependencies:
  - name: postgresql
    version: 12.10.0
    repository: https://charts.bitnami.com/bitnami
    alias: postgres
  # If we want to use custom charts we can just put them in this repo and use `file://`
  - name: external-dns
    version: 6.14.3
    repository: https://charts.bitnami.com/bitnami
    condition: external-dns.enabled
  - name: jwks
    repository: '@weavejwks'
    version: 1.0.0
  - name: redis
    version: 17.8.4
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: nginx
    version: 13.2.29
    repository: https://charts.bitnami.com/bitnami
    condition: nginx.enabled
