// Code generated by lab.weave.nl/weave/generator, DO NOT EDIT.

package graphql

import (
	"context"

	"lab.weave.nl/nid/nid-core/svc/info-manager/models"
)

func (t *CreateScript) ToModel(ctx context.Context, r *Resolver) (m models.Script, err error) {
	m.Description = t.Description
	m.Name = t.Name
	m.Status = t.Status
	return m, nil
}

func (t *CreateScript) containsField(field string) bool {
	switch field {
	}
	return false
}

func (t *UpdateScript) ToModel(ctx context.Context, r *Resolver) (m models.Script, err error) {
	if t.Description != nil {
		m.Description = *t.Description
	}
	if t.Name != nil {
		m.Name = *t.Name
	}
	if t.Status != nil {
		m.Status = *t.Status
	}
	return m, nil
}

func (t *UpdateScript) containsField(field string) bool {
	switch field {
	case "Description":
		if t.Description != nil {
			return true
		}
	case "Name":
		if t.Name != nil {
			return true
		}
	case "Status":
		if t.Status != nil {
			return true
		}
	}
	return false
}
